foxtry2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

handler404 = 'main.views.view_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('kontakt/', contact, name='contact'),
    path('uslugi/', services, name='services'),
    path('portfolio/', portfolio, name='portfolio'),
    path('portfolio/<int:id>', view, name='view'),
    path('onas/', about, name='about'),
    path('regulamin/', terms, name='terms'),
    path('faq/', faq, name='faq'),
    path('dziekujemy/', thx, name='thx'),
    path('koszyk/', cart, name='cart'),
    path('podsumowanie/', checkout, name='checkout'),
    path('process_order/', processOrder, name="process_order"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import email
from pyexpat import model
from django.db import models


class Workers(models.Model):
    zdjecie=models.FileField(blank=False)
    imie_i_nazwisko=models.CharField(max_length=100)
    specjalizacja=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    linkedin=models.CharField(max_length=300)

    def __str__(self):
        return self.imie_i_nazwisko
    
    class Meta:
        verbose_name="Pracownik"
        verbose_name_plural="Pracownicy"

class Portfolio(models.Model):
    miniaturka=models.FileField(blank=False)
    logo=models.FileField(blank=True)
    nazwa=models.CharField(max_length=300, blank=False)
    link=models.CharField(max_length=400, blank=True)
    grafika=models.FileField(blank=True)
    grafika_mobilna=models.FileField(blank=True) 
    opis=models.TextField(blank=True)
   
    class Meta:
        verbose_name="Portfolio"
        verbose_name_plural="Portfolio"
    
    def __str__(self):
        return self.nazwa

class PortfolioRowType(models.Model):
    def __str__(self):
        return self.nazwa
    nazwa = models.CharField(max_length=60)

class PortfolioRow(models.Model):
    portfolio = models.ForeignKey(Portfolio, default=None, on_delete=models.CASCADE)
    portfolioRowType = models.ForeignKey(PortfolioRowType, null=True, blank=True, on_delete=models.CASCADE)
    photo1 = models.FileField(blank=True)
    photo2 = models.FileField(blank=True)

    def __str__(self):
        return self.portfolio.nazwa

class PortfolioVideo(models.Model):
    portfolio = models.ForeignKey(Portfolio, default=None, on_delete=models.CASCADE)
    link = models.CharField(max_length=300)

    def __str__(self):
        return self.portfolio.nazwa

class Service(models.Model):
    nazwa = models.CharField(max_length=300)
    opis = models.TextField(max_length=400)
    cena = models.DecimalField(max_digits=8, decimal_places=2)
    cena_wyswietlana = models.CharField(max_length=100)
    zdjecie = models.FileField(blank=False)

    class Meta:
        verbose_name = "Usługa"
        verbose_name_plural = "Usługi"

    def __str__(self):
        return self.nazwa

class Customer(models.Model):
    imie = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    firma = models.CharField(max_length=200, null=True)
    numer = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.imie

    class Meta:
        verbose_name = "Klient"
        verbose_name_plural = "Klienci"

class Order(models.Model):
    klient = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    data_zamowienia = models.DateTimeField(auto_now_add=True)
    ukonczone = models.BooleanField(default=False, null=True, blank=False)
    id_zamowienia = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = "Zamówienie"
        verbose_name_plural = "Zamówienia"

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.ilosc for item in orderitems])
        return total

class OrderItem(models.Model):
    usluga = models.ForeignKey(Service, on_delete=models.SET_NULL, blank=True, null=True)
    zamowienie = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    ilosc = models.IntegerField(default=0, null=True, blank=True)
    data_dodania = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.usluga.cena * self.ilosc
        return total

main/views.py
import json
from django.shortcuts import redirect, render
from main.models import *
import time
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from foxtry2 import settings
import requests
import datetime
from django.http import JsonResponse
from main.utils import cookieCart, cartData, guestOrder

def home(request):
    context = {'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/home.html', context)

def contact(request):
    if request.method == 'POST':
        captcha_token=request.POST.get("g-recaptcha-response")
        captcha_url="https://www.google.com/recaptcha/api/siteverify"
        captcha_secret=settings.GOOGLE_RECAPTCHA_SECRET_KEY
        captcha_data={"secret":captcha_secret,"response":captcha_token}
        captcha_server_response=requests.post(url=captcha_url, data=captcha_data)
        captcha_json=json.loads(captcha_server_response.text)

        if captcha_json['success']==False:
            return redirect('main:contact')
        else:
            name = request.POST.get('fullname')
            email = request.POST.get('email')
            subject = request.POST.get('subject')
            message = request.POST.get('message')

            data = {
                'name': name,
                'email': email,
                'subject': subject,
                'message': message
            }

            temat = data['subject'] + " - " + data['name']
            html_content = render_to_string("main/nowa_wiadomosc.html", data)
            text_content = strip_tags(html_content)
            emaill = EmailMultiAlternatives(
                #temat
                temat,
                #tresc
                text_content,
                #od
                settings.EMAIL_HOST_USER,
                #do
                ['szymon.kalkowski@wp.pl', 'foxsentertainmentgroup@gmail.com']
            )
            emaill.attach_alternative(html_content, "text/html")
            emaill.send()

            temat2 = "Dziękujemy za wiadomość! - Foxtry"
            html_content2 = render_to_string("main/dziekujemy_wiadomosc.html", data)
            text_content2 = strip_tags(html_content2)
            emaill2 = EmailMultiAlternatives(
                #temat
                temat2,
                #tresc
                text_content2,
                #od
                settings.EMAIL_HOST_USER,
                #do
                [data['email']]
            )
            emaill2.attach_alternative(html_content2, "text/html")
            emaill2.send()
            
            time.sleep(3)
    context = {'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/contact.html', context)

def services(request):
    data  = cartData(request)
    cartItems = data['cartItems']
    services = Service.objects.all()
    context = {'services': services, 'cartItems': cartItems, 'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/services.html', context)

def cart(request):
    data  = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'items':items, 'order':order, 'cartItems':cartItems, 'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/cart.html', context)

def checkout(request):
    data  = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'items':items, 'order':order, 'cartItems':cartItems, 'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/checkout.html', context)

def portfolio(request):
    views=Portfolio.objects.all()
    context={'views':views, 'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/portfolio.html', context)

def view(request, id):
    view = Portfolio.objects.get(id=id)
    rows = PortfolioRow.objects.filter(portfolio=view)
    videos = PortfolioVideo.objects.filter(portfolio=view)
    context = {'view':view, 'rows':rows, 'videos':videos, 'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/view.html', context)

def about(request):
    workers=Workers.objects.all()
    context={'workers':workers, 'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/about.html', context)

def terms(request):
    context = {'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/terms.html', context)

def faq(request):
    context = {'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/faq.html', context)

def thx(request):
    context = {'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/thx.html', context)

def view_404(request, exception):
    context = {'secret_ga':settings.GOOGLE_ANALYTICS}
    return render(request, 'main/404.html', context)

from django.views.decorators.csrf import csrf_exempt

@csrf_exempt

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    customer, order = guestOrder(request, data)
    total = float(data['form']['total'].replace(",", "."))
    order.id_zamowienia = transaction_id
    if total == order.get_cart_total:
        order.ukonczone = True
    order.save()
    
    temat="Nowe zmówienie - " + data['form']['fullname']
    html_content = render_to_string("main/nowe_zamowienie.html", {'data':data['form']})
    text_content = strip_tags(html_content)
    emaill = EmailMultiAlternatives(
        #temat  
        temat,
        #tresc
        text_content,
        #od
        settings.EMAIL_HOST_USER,
        #do
        ['szymon.kalkowski@wp.pl', 'foxsentertainmentgroup@gmail.com']
    )
    emaill.attach_alternative(html_content, "text/html")
    emaill.send()

    temat2="Dziękujemy za zamówienie - Foxtry"
    html_content2 = render_to_string("main/dziekujemy_zamowienie.html", {'data': data['form']})
    text_content2 = strip_tags(html_content2)
    emaill2 = EmailMultiAlternatives(
        #temat
        temat2,
        #tresc
        text_content2,
        #od
        settings.EMAIL_HOST_USER,
        #do
        [data['form']['email']]
    )
    emaill2.attach_alternative(html_content2, "text/html")
    emaill2.send()

    return JsonResponse('Order complete', safe=False)

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Lato:wght@300;400;700&family=Playfair+Display:ital,wght@1,600&family=Rajdhani:wght@500&family=Raleway:wght@100&family=Tapestry&display=swap%27" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col-12 p-3">
            <h1 class="fx red">FOXTRY</h1>
            <h3 class="text-white">Foxtry jest grupą założoną w 2018 roku. Od tego czasu staramy się dostarczać naszym klientom najwyższej jakości grafiki i dostosowywać ceny do ich budżetów i potrzeb. Uważamy, że kontakt z klientem jest najważniejszą rzeczą podczas naszej pracy, dzięki czemu dostajesz gwarancje zadowolenia i jakości.</h3>
        </div>
        {% for worker in workers %}
        <div class="col-12 col-lg-4">
            <img class="w-75 d-block mx-auto m-1" src="{{worker.zdjecie.url}}">
            <h1 class="text-center red name">{{worker.imie_i_nazwisko}}</h1>
            <h4 class="text-white text-center">{{worker.specjalizacja}}</h4>
            <h5 class="text-center"><a class="text-white text-decoration-none" href="mailto:{{worker.email}}">{{worker.email}}</a></h5>
            <h5 class="text-center"><a class="text-white" target="_blank" href="{{worker.linkedin}}">LinkedIn</a></h5>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var element = document.getElementById("onas");
    element.classList.add("active");
</script>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl" prefix="og: https://ogp.me/ns#">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Jako grupa Foxtry tworzymy wysokiej jakości grafiki, filmy i strony internetowe. Stale aktualizujemy nasze portfolio, a najważniejszy jest dla nas dobry kontakt z klientem.">
    <meta name="keywords" content="foxtry, strony internetowe, grafiki, montaż">
    <meta property="og:image" content="https://i.imgur.com/ffC8zdC.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#1f1f1f">
    <meta name="msapplication-TileColor" content="#1f1f1f">
    <meta name="theme-color" content="#1f1f1f">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{secret_ga}}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{secret_ga}}');
    </script>

    <script type="text/javascript">
      function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken')
    
      function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");
    
            // Loop through the array elements
            for(var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");
    
                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if(name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }
    
            // Return null if not found
            return null;
        }
        var cart = JSON.parse(getCookie('cart'))
    
        if (cart == undefined){
          cart = {}
          console.log('Cart Created!', cart)
          document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)
    </script>
    
    {% block head %}{% endblock head %}

    <title>Foxtry</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-2" aria-label="Fourth navbar example">
        <div class="container-fluid">
          <a class="navbar-brand d-block d-lg-none" href="{% url 'main:home' %}"><img class="p-3 logo" src="{% static 'img/logo.svg' %}"></a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            
            <span class="toggler-icon top-bar"></span>
            <span class="toggler-icon middle-bar"></span>
            <span class="toggler-icon bottom-bar"></span>
          </button>
    
          <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto w-100 d-flex justify-content-around">
              <li class="nav-item my-auto mx-3">
                <a class="nav-link" id="kontakt" aria-current="page" href="{% url 'main:contact' %}">KONTAKT</a>
              </li>
              <li class="nav-item my-auto mx-3">
                <a class="nav-link" id="uslugi" href="{% url 'main:services' %}">USŁUGI</a>
              </li>
              <li class="nav-item my-auto">
                <a class="nav-link d-none d-lg-flex justify-content-center" href="{% url 'main:home' %}" id="logo"><img class="p-1 logo" src="{% static 'img/logo.svg' %}"></a>
              </li>
              <li class="nav-item my-auto mx-3">
                <a class="nav-link" id="portfolio" href="{% url 'main:portfolio' %}">PORTFOLIO</a>
              </li>
              <li class="nav-item my-auto mx-3">
                <a class="nav-link" id="onas" href="{% url 'main:about' %}">O NAS</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}{% endblock content %}
    <footer id="f" class="mt-auto">
      <div class="socials">
        <div><a href="https://www.instagram.com/foxtrygraphics/" target="_blank" class="w-100"><img src="{% static 'img/ig.svg' %}"></a></div>
        <div><a href="https://www.facebook.com/FOKSPRODUCTION" target="_blank" class="w-100"><img src="{% static 'img/fb.svg' %}"></a></div>
        <div><a href="https://www.youtube.com/channel/UC-ZCEz2zFDyiEnYb37aomVQ" target="_blank" class="w-100"><img src="{% static 'img/yt.svg'%}"></a></div>
        <div><a href="https://discord.gg/w245Py8hFA" target="_blank" class="w-100"><img src="{% static 'img/dc.svg' %}"></a></div>
      </div>
      <p class="p1">Foxtry.pl</p>
      <p class="p2">@2021. All rights reserved.</p>
      <div class="divf">
        <a href="{% url 'main:contact' %}" class="text-right">Kontakt</a><a href="{% url 'main:terms' %}">Regulamin</a><a href="{% url 'main:faq' %}" class="text-center">FAQ</a>
      </div>
    </footer>
    <div class="cookie-container">
      <p>
        Używamy plików cookies w celu zapewnienia jak najlepszych doświadczeń podczas przeglądania naszej strony. Aby dowiedzieć się więcej przeczytaj
        <a href="{% static 'pdf/politykaprywatnosci_foxtry.pdf' %}" target="_blank">politykę prywatności</a> i <a href="{% static 'pdf/politykacookies_foxtry.pdf' %}" target="_blank">politykę cookies</a>.
      </p>
      <div>
        <button class="cookie-btn btn my-3">Akceptuję</button>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cookie.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

main/templates/main/cart.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row">
        <a href="{% url 'main:services' %}" class="btn mt-3">&#x2190; Powrót do usług</a>
        <div class="row cart-header">
            <div class="col-6 col-lg-4">
                <h4 class="red">Usługi: {{order.get_cart_items}}</h4>
            </div>
            <div class="col-6 col-lg-4">
                <h4 class="red">Suma: {{order.get_cart_total|floatformat:2}}PLN</h4>
            </div>
            <div class="col-12 col-lg-4">
                <a href="{% url 'main:checkout' %}" class="btn mx-auto d-block my-3">Podsumowanie</a>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-2">

            </div>
            <div class="col-5">
                <h4 class="red">Usługa</h4>
            </div>
            <div class="col-3">
                <h4 class="red">Cena</h4>
            </div>
            <div class="col-2">
                <h4 class="red">Ilość</h4>
            </div>
        </div>
        {% for item in items %}
        <div class="row cart-row">
            <div class="col-2">
                <img class="w-100" src="{{item.service.zdjecie}}">
            </div>
            <div class="col-5">
                <h4 class="red">{{item.service.nazwa}}</h4>
            </div>
            <div class="col-3">
                <h4 class="red">{{item.service.cena_wyswietlana}}</h4>
            </div>
            <div class="col-2">
                <h4 class="red">{{item.ilosc}}x</h4>
                <div class="pm">
                    <div data-product="{{item.service.id}}" data-action="add" class="update-cart red">+</div>
                    <div data-product="{{item.service.id}}" data-action="remove" class="update-cart red">-</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var element = document.getElementById("uslugi");
    element.classList.add("active");
</script>
{% endblock %}

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}
{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col-12">
            <div class="mx-auto d-flex flex-column align-items-center">
                <h4 class="sent-notification"></h4>
                <h1 class="red">KONTAKT</h1>
                <h2 class="skontaktuj">SKONTAKTUJ SIĘ Z NAMI!</h2>
                <form class="d-flex flex-column align-items-start" id="myForm" action="" method="POST">
                    {% csrf_token %}
                    <label class="mt-4">Imię</label>
                    <input id="fullname" type="text" placeholder="" name="fullname" required>
                    <label class="mt-4">Email</label>
                    <input id="email" type="text" placeholder="" name="email" required>
                    <label class="mt-4">Temat</label>
                    <input id="subject" type="text" placeholder="" name="subject" required>
                    <label class="mt-4">Treść</label>
                    <textarea id="body" rows="5" placeholder="" name="message"></textarea>
                    <div class="g-recaptcha mt-4" data-theme="dark" data-sitekey="6Lc6a5wfAAAAADU9UqEISL4H2iWY48h6Tr0n6V9K"></div>
                    <button id="button" class="mt-4 align-self-center align-self-lg-end" type="submit" data-action='submit' onclick="funkcja()" value="Send An Email">WYŚLIJ</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var element = document.getElementById("kontakt");
    element.classList.add("active");
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    function funkcja(){
        if (email.value != '' && subject.value != '' && fullname.value != ''){
            setTimeout(function(){
                $('.sent-notification').text("Wiadomość wysłana pomyślnie!");
            },1000);
		}
	}
</script>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Lato:wght@300;400;700&family=Playfair+Display:ital,wght@1,600&family=Rajdhani:wght@500&family=Raleway:wght@100&family=Tapestry&display=swap%27" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="animation">
    <div class="karton">
        <span class="fx-anim">
        <h1 class="change-text">Foxtry.pl</h1>
        </span>
    </div>
    
    <p class="subtitle">Find your way.</p>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var element = document.getElementById("f");
    element.classList.add("dnone");
</script>
{% endblock %}

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3 mb-5">
    <div class="row">
        {% for view in views %}
        <div class="col-12 col-md-4 col-lg-3 p-5">
            <a class="d-block w-100 position-relative" href="{% url 'main:portfolio' %}{{view.id}}"><img class="w-100" src="{{view.miniaturka.url}}"><div class="hov"><p class="m-0">ZOBACZ</p><b class="m-0">WIĘCEJ</b></div></a>
            <h3 class="text-white mt-3">{{view.nazwa}}</h3>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var element = document.getElementById("portfolio");
    element.classList.add("active");
</script>
{% endblock %}

main/templates/main/services.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row">
        {% for service in services %}
        <div class="col-12 col-lg-4 p-5">
            <div class="item">
                <img src="{{service.zdjecie.url}}" class="w-75 mx-auto d-block">
                <h1 class="text-center red font-weight-bold">{{service.nazwa}}</h1>
                <h5 class="text-white text-center p-3">{{service.opis}}</h5>
                <h2 class="text-center red font-weight-bold">{{service.cena_wyswietlana}}</h2>
                <button data-product="{{service.id}}" data-action="add" class="orderbtn update-cart">ZAMÓW</button>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="cart">
	<a href="{% url 'main:cart' %}">
		<img id="cart-icon" src="{% static 'img/cart.svg' %}">
	</a>
	<p id="cart-total">{{cartItems}}</p>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    var element = document.getElementById("uslugi");
    element.classList.add("active");
</script>
{% endblock %}

main/templates/main/thx.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container mb-5">
    <div class="row">
        <img src="{% static 'img/truck.svg' %}" class="mx-auto mt-5" style="width: 200px">
        <h1 class="red text-center my-3">Dziękujemy za złożenie zamówienia!</h1>
        <h3 class="text-white text-center my-3">Twoje zamówienie dotarło już do naszych pracowników i zostanie zrealizowane najszybciej jak to możliwe. Wiadomość zwrotną dostaniesz na maila podanego w formularzu. Dziękujemy za wybranie Foxtry!</h3>
        <a class="btn mx-auto my-3" href="{% url 'main:home' %}">Powrót na stronę główną</a>
    </div>
</div>
{% endblock %}
{% block scripts %}

{% endblock %}